#ifndef MMP_COMPARE_H
#define MMP_COMPARE_H

/* MMP_COMPARE_TEMPLATES_FOR_LOGIC */

#define COMPARE__(_X) _X

#define COMPARE_a(_X) _X
#define COMPARE_b(_X) _X
#define COMPARE_c(_X) _X
#define COMPARE_d(_X) _X
#define COMPARE_e(_X) _X
#define COMPARE_f(_X) _X
#define COMPARE_g(_X) _X
#define COMPARE_h(_X) _X
#define COMPARE_i(_X) _X
#define COMPARE_j(_X) _X
#define COMPARE_k(_X) _X
#define COMPARE_l(_X) _X
#define COMPARE_m(_X) _X
#define COMPARE_n(_X) _X
#define COMPARE_o(_X) _X
#define COMPARE_p(_X) _X
#define COMPARE_q(_X) _X
#define COMPARE_r(_X) _X
#define COMPARE_s(_X) _X
#define COMPARE_t(_X) _X
#define COMPARE_u(_X) _X
#define COMPARE_v(_X) _X
#define COMPARE_w(_X) _X
#define COMPARE_x(_X) _X
#define COMPARE_y(_X) _X
#define COMPARE_z(_X) _X

#define COMPARE_A(_X) _X
#define COMPARE_B(_X) _X
#define COMPARE_C(_X) _X
#define COMPARE_D(_X) _X
#define COMPARE_E(_X) _X
#define COMPARE_F(_X) _X
#define COMPARE_G(_X) _X
#define COMPARE_H(_X) _X
#define COMPARE_I(_X) _X
#define COMPARE_J(_X) _X
#define COMPARE_K(_X) _X
#define COMPARE_L(_X) _X
#define COMPARE_M(_X) _X
#define COMPARE_N(_X) _X
#define COMPARE_O(_X) _X
#define COMPARE_P(_X) _X
#define COMPARE_Q(_X) _X
#define COMPARE_R(_X) _X
#define COMPARE_S(_X) _X
#define COMPARE_T(_X) _X
#define COMPARE_U(_X) _X
#define COMPARE_V(_X) _X
#define COMPARE_W(_X) _X
#define COMPARE_X(_X) _X
#define COMPARE_Y(_X) _X
#define COMPARE_Z(_X) _X

#define COMPARE_asm(_X)              _X
#define COMPARE_and(_X)              _X
#define COMPARE_and_eq(_X)           _X
#define COMPARE_auto(_X)             _X
#define COMPARE_bitand(_X)           _X
#define COMPARE_bitor(_X)            _X
#define COMPARE_bool(_X)             _X
#define COMPARE_break(_X)            _X
#define COMPARE_case(_X)             _X
#define COMPARE_catch(_X)            _X
#define COMPARE_char(_X)             _X
#define COMPARE_class(_X)            _X
#define COMPARE_compl(_X)            _X
#define COMPARE_const(_X)            _X
#define COMPARE_const_cast(_X)       _X
#define COMPARE_continue(_X)         _X
#define COMPARE_default(_X)          _X
#define COMPARE_define(_X)           _X
#define COMPARE_defined(_X)          _X
#define COMPARE_delete(_X)           _X
#define COMPARE_do(_X)               _X
#define COMPARE_double(_X)           _X
#define COMPARE_dynamic_cast(_X)     _X
#define COMPARE_else(_X)             _X
#define COMPARE_elif(_X)             _X
#define COMPARE_endif(_X)            _X
#define COMPARE_enum(_X)             _X
#define COMPARE_error(_X)            _X
#define COMPARE_explicit(_X)         _X
#define COMPARE_export(_X)           _X
#define COMPARE_extern(_X)           _X
#define COMPARE_false(_X)            _X
#define COMPARE_float(_X)            _X
#define COMPARE_for(_X)              _X
#define COMPARE_friend(_X)           _X
#define COMPARE_goto(_X)             _X
#define COMPARE_if(_X)               _X
#define COMPARE_ifdef(_X)            _X
#define COMPARE_ifndef(_X)           _X
#define COMPARE_include(_X)          _X
#define COMPARE_inline(_X)           _X
#define COMPARE_int(_X)              _X
#define COMPARE_line(_X)             _X
#define COMPARE_long(_X)             _X
#define COMPARE_mutable(_X)          _X
#define COMPARE_namespace(_X)        _X
#define COMPARE_new(_X)              _X
#define COMPARE_not(_X)              _X
#define COMPARE_not_eq(_X)           _X
#define COMPARE_operator(_X)         _X
#define COMPARE_or(_X)               _X
#define COMPARE_or_eq(_X)            _X
#define COMPARE_pragma(_X)           _X
#define COMPARE_private(_X)          _X
#define COMPARE_protected(_X)        _X
#define COMPARE_public(_X)           _X
#define COMPARE_register(_X)         _X
#define COMPARE_reinterpret_cast(_X) _X
#define COMPARE_restrict(_X)         _X
#define COMPARE_return(_X)           _X
#define COMPARE_short(_X)            _X
#define COMPARE_signed(_X)           _X
#define COMPARE_sizeof(_X)           _X
#define COMPARE_static(_X)           _X
#define COMPARE_static_cast(_X)      _X
#define COMPARE_struct(_X)           _X
#define COMPARE_switch(_X)           _X
#define COMPARE_template(_X)         _X
#define COMPARE_this(_X)             _X
#define COMPARE_throw(_X)            _X
#define COMPARE_true(_X)             _X
#define COMPARE_try(_X)              _X
#define COMPARE_typedef(_X)          _X
#define COMPARE_typeid(_X)           _X
#define COMPARE_typename(_X)         _X
#define COMPARE_undef(_X)            _X
#define COMPARE_union(_X)            _X
#define COMPARE_unsigned(_X)         _X
#define COMPARE_using(_X)            _X
#define COMPARE_virtual(_X)          _X
#define COMPARE_void(_X)             _X
#define COMPARE_volatile(_X)         _X
#define COMPARE_wchar_t(_X)          _X
#define COMPARE_while(_X)            _X
#define COMPARE_xor(_X)              _X
#define COMPARE_xor_eq(_X)           _X

#define COMPARE_0(_X)   _X
#define COMPARE_1(_X)   _X
#define COMPARE_2(_X)   _X
#define COMPARE_3(_X)   _X
#define COMPARE_4(_X)   _X
#define COMPARE_5(_X)   _X
#define COMPARE_6(_X)   _X
#define COMPARE_7(_X)   _X
#define COMPARE_8(_X)   _X
#define COMPARE_9(_X)   _X
#define COMPARE_10(_X)  _X
#define COMPARE_11(_X)  _X
#define COMPARE_12(_X)  _X
#define COMPARE_13(_X)  _X
#define COMPARE_14(_X)  _X
#define COMPARE_15(_X)  _X
#define COMPARE_16(_X)  _X
#define COMPARE_17(_X)  _X
#define COMPARE_18(_X)  _X
#define COMPARE_19(_X)  _X
#define COMPARE_20(_X)  _X
#define COMPARE_21(_X)  _X
#define COMPARE_22(_X)  _X
#define COMPARE_23(_X)  _X
#define COMPARE_24(_X)  _X
#define COMPARE_25(_X)  _X
#define COMPARE_26(_X)  _X
#define COMPARE_27(_X)  _X
#define COMPARE_28(_X)  _X
#define COMPARE_29(_X)  _X
#define COMPARE_30(_X)  _X
#define COMPARE_31(_X)  _X
#define COMPARE_32(_X)  _X
#define COMPARE_33(_X)  _X
#define COMPARE_34(_X)  _X
#define COMPARE_35(_X)  _X
#define COMPARE_36(_X)  _X
#define COMPARE_37(_X)  _X
#define COMPARE_38(_X)  _X
#define COMPARE_39(_X)  _X
#define COMPARE_40(_X)  _X
#define COMPARE_41(_X)  _X
#define COMPARE_42(_X)  _X
#define COMPARE_43(_X)  _X
#define COMPARE_44(_X)  _X
#define COMPARE_45(_X)  _X
#define COMPARE_46(_X)  _X
#define COMPARE_47(_X)  _X
#define COMPARE_48(_X)  _X
#define COMPARE_49(_X)  _X
#define COMPARE_50(_X)  _X
#define COMPARE_51(_X)  _X
#define COMPARE_52(_X)  _X
#define COMPARE_53(_X)  _X
#define COMPARE_54(_X)  _X
#define COMPARE_55(_X)  _X
#define COMPARE_56(_X)  _X
#define COMPARE_57(_X)  _X
#define COMPARE_58(_X)  _X
#define COMPARE_59(_X)  _X
#define COMPARE_60(_X)  _X
#define COMPARE_61(_X)  _X
#define COMPARE_62(_X)  _X
#define COMPARE_63(_X)  _X
#define COMPARE_64(_X)  _X
#define COMPARE_65(_X)  _X
#define COMPARE_66(_X)  _X
#define COMPARE_67(_X)  _X
#define COMPARE_68(_X)  _X
#define COMPARE_69(_X)  _X
#define COMPARE_70(_X)  _X
#define COMPARE_71(_X)  _X
#define COMPARE_72(_X)  _X
#define COMPARE_73(_X)  _X
#define COMPARE_74(_X)  _X
#define COMPARE_75(_X)  _X
#define COMPARE_76(_X)  _X
#define COMPARE_77(_X)  _X
#define COMPARE_78(_X)  _X
#define COMPARE_79(_X)  _X
#define COMPARE_80(_X)  _X
#define COMPARE_81(_X)  _X
#define COMPARE_82(_X)  _X
#define COMPARE_83(_X)  _X
#define COMPARE_84(_X)  _X
#define COMPARE_85(_X)  _X
#define COMPARE_86(_X)  _X
#define COMPARE_87(_X)  _X
#define COMPARE_88(_X)  _X
#define COMPARE_89(_X)  _X
#define COMPARE_90(_X)  _X
#define COMPARE_91(_X)  _X
#define COMPARE_92(_X)  _X
#define COMPARE_93(_X)  _X
#define COMPARE_94(_X)  _X
#define COMPARE_95(_X)  _X
#define COMPARE_96(_X)  _X
#define COMPARE_97(_X)  _X
#define COMPARE_98(_X)  _X
#define COMPARE_99(_X)  _X
#define COMPARE_100(_X) _X
#define COMPARE_101(_X) _X
#define COMPARE_102(_X) _X
#define COMPARE_103(_X) _X
#define COMPARE_104(_X) _X
#define COMPARE_105(_X) _X
#define COMPARE_106(_X) _X
#define COMPARE_107(_X) _X
#define COMPARE_108(_X) _X
#define COMPARE_109(_X) _X
#define COMPARE_110(_X) _X
#define COMPARE_111(_X) _X
#define COMPARE_112(_X) _X
#define COMPARE_113(_X) _X
#define COMPARE_114(_X) _X
#define COMPARE_115(_X) _X
#define COMPARE_116(_X) _X
#define COMPARE_117(_X) _X
#define COMPARE_118(_X) _X
#define COMPARE_119(_X) _X
#define COMPARE_120(_X) _X
#define COMPARE_121(_X) _X
#define COMPARE_122(_X) _X
#define COMPARE_123(_X) _X
#define COMPARE_124(_X) _X
#define COMPARE_125(_X) _X
#define COMPARE_126(_X) _X
#define COMPARE_127(_X) _X
#define COMPARE_128(_X) _X
#define COMPARE_129(_X) _X
#define COMPARE_130(_X) _X
#define COMPARE_131(_X) _X
#define COMPARE_132(_X) _X
#define COMPARE_133(_X) _X
#define COMPARE_134(_X) _X
#define COMPARE_135(_X) _X
#define COMPARE_136(_X) _X
#define COMPARE_137(_X) _X
#define COMPARE_138(_X) _X
#define COMPARE_139(_X) _X
#define COMPARE_140(_X) _X
#define COMPARE_141(_X) _X
#define COMPARE_142(_X) _X
#define COMPARE_143(_X) _X
#define COMPARE_144(_X) _X
#define COMPARE_145(_X) _X
#define COMPARE_146(_X) _X
#define COMPARE_147(_X) _X
#define COMPARE_148(_X) _X
#define COMPARE_149(_X) _X
#define COMPARE_150(_X) _X
#define COMPARE_151(_X) _X
#define COMPARE_152(_X) _X
#define COMPARE_153(_X) _X
#define COMPARE_154(_X) _X
#define COMPARE_155(_X) _X
#define COMPARE_156(_X) _X
#define COMPARE_157(_X) _X
#define COMPARE_158(_X) _X
#define COMPARE_159(_X) _X
#define COMPARE_160(_X) _X
#define COMPARE_161(_X) _X
#define COMPARE_162(_X) _X
#define COMPARE_163(_X) _X
#define COMPARE_164(_X) _X
#define COMPARE_165(_X) _X
#define COMPARE_166(_X) _X
#define COMPARE_167(_X) _X
#define COMPARE_168(_X) _X
#define COMPARE_169(_X) _X
#define COMPARE_170(_X) _X
#define COMPARE_171(_X) _X
#define COMPARE_172(_X) _X
#define COMPARE_173(_X) _X
#define COMPARE_174(_X) _X
#define COMPARE_175(_X) _X
#define COMPARE_176(_X) _X
#define COMPARE_177(_X) _X
#define COMPARE_178(_X) _X
#define COMPARE_179(_X) _X
#define COMPARE_180(_X) _X
#define COMPARE_181(_X) _X
#define COMPARE_182(_X) _X
#define COMPARE_183(_X) _X
#define COMPARE_184(_X) _X
#define COMPARE_185(_X) _X
#define COMPARE_186(_X) _X
#define COMPARE_187(_X) _X
#define COMPARE_188(_X) _X
#define COMPARE_189(_X) _X
#define COMPARE_190(_X) _X
#define COMPARE_191(_X) _X
#define COMPARE_192(_X) _X
#define COMPARE_193(_X) _X
#define COMPARE_194(_X) _X
#define COMPARE_195(_X) _X
#define COMPARE_196(_X) _X
#define COMPARE_197(_X) _X
#define COMPARE_198(_X) _X
#define COMPARE_199(_X) _X
#define COMPARE_200(_X) _X
#define COMPARE_201(_X) _X
#define COMPARE_202(_X) _X
#define COMPARE_203(_X) _X
#define COMPARE_204(_X) _X
#define COMPARE_205(_X) _X
#define COMPARE_206(_X) _X
#define COMPARE_207(_X) _X
#define COMPARE_208(_X) _X
#define COMPARE_209(_X) _X
#define COMPARE_210(_X) _X
#define COMPARE_211(_X) _X
#define COMPARE_212(_X) _X
#define COMPARE_213(_X) _X
#define COMPARE_214(_X) _X
#define COMPARE_215(_X) _X
#define COMPARE_216(_X) _X
#define COMPARE_217(_X) _X
#define COMPARE_218(_X) _X
#define COMPARE_219(_X) _X
#define COMPARE_220(_X) _X
#define COMPARE_221(_X) _X
#define COMPARE_222(_X) _X
#define COMPARE_223(_X) _X
#define COMPARE_224(_X) _X
#define COMPARE_225(_X) _X
#define COMPARE_226(_X) _X
#define COMPARE_227(_X) _X
#define COMPARE_228(_X) _X
#define COMPARE_229(_X) _X
#define COMPARE_230(_X) _X
#define COMPARE_231(_X) _X
#define COMPARE_232(_X) _X
#define COMPARE_233(_X) _X
#define COMPARE_234(_X) _X
#define COMPARE_235(_X) _X
#define COMPARE_236(_X) _X
#define COMPARE_237(_X) _X
#define COMPARE_238(_X) _X
#define COMPARE_239(_X) _X
#define COMPARE_240(_X) _X
#define COMPARE_241(_X) _X
#define COMPARE_242(_X) _X
#define COMPARE_243(_X) _X
#define COMPARE_244(_X) _X
#define COMPARE_245(_X) _X
#define COMPARE_246(_X) _X
#define COMPARE_247(_X) _X
#define COMPARE_248(_X) _X
#define COMPARE_249(_X) _X
#define COMPARE_250(_X) _X
#define COMPARE_251(_X) _X
#define COMPARE_252(_X) _X
#define COMPARE_253(_X) _X
#define COMPARE_254(_X) _X
#define COMPARE_255(_X) _X
#define COMPARE_256(_X) _X

#endif // !MMP_COMPARE_H
